language: node_js
node_js:
  - "0.10"

env:
  global:
    - secure: YHeLGpWj+UjeWyYgOutYq/8MeMthE2LKjlp9EEq47tTwYS1NGOd0UwvEhBevIsHj4/rI5TpPbdQ9lkW6erdmAxN+E9crBOfnMQsqAlKbXBA/yv0JSOoC7kBnO53RBe0fnpCiMEAhz7H2tYknV+xjMCpqHl5jKr0XusLZZ2qI+A4=
    - secure: I7V2n5hxhkHBq0LOJnAzhGVThjtfLpGisZo9F7bvfQM0QnPIpP/LvEQl71FMNpq6aCNtjdzv1AYLcAw10lZx9HtQL/P4OU77qV/3AAGYE+bonAmMKb/+s+e6rZx2JXWAe2WhleMVtRFIdSxF8CUeyX2j+4X30FPrEn9AgZ0SmvA=

script: grunt saucelabs;